
language: node_js
node_js:
  - '8'
script:
  - yarn prettier:list
  - yarn flow
  - yarn lint
  - yarn test
  - yarn build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: storybook-static
  on:
    branch: master